---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, 
summary: 若要使用 BlueXP 勒索軟體保護、請執行幾個步驟來設定。 
---
= 設定 BlueXP 勒索軟體保護
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: /media/


[role="lead"]
若要使用 BlueXP 勒索軟體保護、請執行幾個步驟來設定。

開始之前、請先檢閱 link:rp-start-prerequisites.html["先決條件"] 確保您的環境已準備就緒。



== 準備備備份目的地

準備下列其中一個備份目的地：

* NetApp StorageGRID
* Amazon Web Services


在備份目的地本身設定選項之後、您稍後會在 BlueXP 勒索軟體保護服務中將其設定為備份目的地。



=== 準備 StorageGRID 成為備份目的地

如果您想要使用 StorageGRID 做為備份目的地、請參閱 https://docs.netapp.com/us-en/storagegrid-117/index.html["本文檔StorageGRID"^] 如需 StorageGRID 的詳細資訊、



=== 準備 AWS 成為備份目的地

* 在 AWS 中設定帳戶。
* 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS權限"^] 在 AWS 中。


如需在 BlueXP 中管理 AWS 儲存設備的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["管理您的Amazon S3儲存庫"^]。



== 設定 BlueXP

下一步是設定 BlueXP 和 BlueXP 勒索軟體保護服務。

檢閱 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準 BlueXP 需求"^]。



=== 在 BlueXP 中建立 Connector

您應該聯絡 NetApp 銷售代表、試用這項服務。然後、當您使用 BlueXP Connector 時、它會包含勒索軟體保護服務的適當功能。

若要在使用此服務之前在 BlueXP 中建立 Connector 、請參閱說明的 BlueXP 文件 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何建立 BlueXP Connector"^]。


NOTE: 如果您有多個 BlueXP Connectors 、服務將會掃描 BlueXP UI 目前所顯示以外的所有 Connectors 資料。此服務會探索與此帳戶相關的所有工作區和所有 Connector 。



=== 存取 BlueXP 勒索軟體保護

您可以使用 NetApp BlueXP 登入 BlueXP 勒索軟體保護服務。從 BlueXP 左側瀏覽器中、選取 * 保護 * > * 勒索軟體保護 * 。

如需詳細資訊、請參閱 link:rp-start-login.html["存取 BlueXP 勒索軟體保護"]。



=== 在 BlueXP 勒索軟體保護中設定備份目的地

使用 BlueXP 勒索軟體保護備份目的地選項來設定備份目的地。如需詳細資訊、請參閱 link:rp-use-settings.html["設定設定選項"]。
