---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= BlueXP 勒索軟體保護常見問題集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 部署

* 您是否需要授權才能使用 BlueXP 勒索軟體保護？ *

您可以使用下列授權類型：

* 註冊 30 天免費試用。
* 向 Amazon Web Services （ AWS ） Marketplace ， Google Cloud Marketplace 和 Microsoft Azure Marketplace （即將推出）購買隨用隨付（ PAYGO ）訂閱。
* 請自帶授權（ BYOL ）、這是您從 NetApp 銷售代表處取得的 NetApp 授權檔案（ NLF ）您可以使用授權序號、在 BlueXP 數位錢包中啟動 BYOL 。


* 如何啟用 BlueXP 勒索軟體保護？ *
BlueXP 勒索軟體保護不需要任何啟用。BlueXP 左側導覽會自動啟用勒索軟體保護選項。

若要開始使用、您必須註冊或聯絡 NetApp 銷售代表、才能試用這項服務。然後、當您使用 BlueXP Connector 時、它會包含該服務的適當功能。

若要開始使用 BlueXP  勒索軟體保護功能、請從其初始登陸頁面按一下「開始探索工作負載」。

* BlueXP  勒索軟體保護是否提供標準、限制和私有模式？ *目前、 BlueXP 勒索軟體保護僅適用於標準模式。敬請期待更多資訊。

如需所有 BlueXP 服務中這些模式的說明、請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 部署模式"^]。



== 存取

* 什麼是 BlueXP 勒索軟體保護 URL ？ *對於 URL 、在瀏覽器中輸入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/ransomware-protection"^] 以存取 BlueXP  主控台。

* 如何處理存取權限？ *只有組織管理員才能啟動服務並探索工作負載（因為這涉及使用資源）。後續互動可由任何角色執行。

* 哪種裝置解析度最佳？ *BlueXP 勒索軟體保護的建議裝置解析度為 1920x1080 或更高。

* 我應該使用哪個瀏覽器？ *任何現代化的瀏覽器都能正常運作。



== 與其他服務互動

* BlueXP 勒索軟體保護是否能感知 NetApp ONTAP 中的保護設定？ *
是的、 BlueXP 勒索軟體保護會探索 ONTAP 中設定的 Snapshot 排程。

* 如果您使用 BlueXP 勒索軟體保護設定原則、您是否必須在未來僅在此服務中進行變更？ *
我們建議您從 BlueXP 勒索軟體保護服務進行原則變更。

* BlueXP  勒索軟體保護如何與 BlueXP  備份與還原及 SnapCenter 互動？ *

BlueXP  勒索軟體保護使用下列產品和服務：

* BlueXP  備份與還原、探索及設定檔案共用工作負載的快照與備份原則
* SnapCenter 或 SnapCenter for VMware 可探索及設定應用程式和 VM 工作負載的快照和備份原則。


此外、 BlueXP  勒索軟體保護還使用 BlueXP  備份與還原、以及 SnapCenter / SnapCenter for VMware 來執行檔案與工作負載一致的還原。



== 工作負載

* 工作負載的組成為何？ *工作負載是應用程式、 VM 或檔案共用。工作負載包括單一應用程式執行個體所使用的所有磁碟區。例如、部署在 ora3.host.com 上的 Oracle DB 執行個體、其資料和記錄可分別具有 vol1 和 vol2 。這些磁碟區一起構成 Oracle DB 執行個體的特定執行個體工作負載。

* BlueXP 勒索軟體保護如何優先處理工作負載資料？ *
資料優先順序是由所製作的 Snapshot 複本和排程的備份所決定。

工作負載優先順序（關鍵、標準、重要）是由已套用至與工作負載相關之每個 Volume 的 Snapshot 頻率所決定。

link:rp-use-protect.html["瞭解工作負載優先順序或重要性"]。

* BlueXP  勒索軟體保護支援哪些工作負載？ *

BlueXP  勒索軟體保護可識別下列工作負載： Oracle 、 MySQL 、檔案共用、 VM 和 VM 資料存放區。

此外、如果客戶使用 SnapCenter 或 SnapCenter for VMware 、則這些產品支援的所有工作負載也會透過 BlueXP  勒索軟體保護來識別、而 BlueXP  勒索軟體保護則能以工作負載一致的方式來保護及恢復這些工作負載。

* 如何將資料與工作負載建立關聯？ *

BlueXP  勒索軟體保護會以下列方式將資料與工作負載相關聯：

* BlueXP  勒索軟體保護會探索這些磁碟區和副檔名、並將它們與適當的工作負載建立關聯。
* 此外、如果您擁有 SnapCenter 或 SnapCenter for VMware 、並在 BlueXP  備份與還原中設定工作負載、則 BlueXP  勒索軟體保護會探索由 SnapCenter 和 SnapCenter for VMware 管理的工作負載及其相關磁碟區。


* 什麼是「受保護的」工作負載？ *在 BlueXP  勒索軟體保護中、當工作負載啟用主要偵測原則時、會顯示「受保護」狀態。現在、這表示在所有與工作負載相關的磁碟區上都啟用 ARP 。

* 什麼是「面臨風險」工作負載？ *如果工作負載未啟用主要偵測原則、即使已啟用備份和快照原則、也會有「風險」。

* 新增的 Volume 、但尚未顯示 * 如果您在環境中新增新的 Volume 、請重新啟動探索、並套用保護原則來保護該新的 Volume 。

* 儀表板不會顯示我所有的工作負載。可能出了什麼問題？ *目前僅支援 NFS 和 CIFS 磁碟區。 iSCSI 磁碟區和其他不受支援的組態會被篩選出來、不會出現在儀表板上。



== 保護原則

* BlueXP 勒索軟體原則是否與其他類型的工作負載原則共存？ *
目前、 BlueXP 備份與還原（ Cloud Backup ）支援每個磁碟區一個備份原則。因此、 BlueXP 備份與還原以及 BlueXP 勒索軟體保護功能會共用備份原則。

Snapshot 複本不受限制、可與每項服務分開新增。

* 勒索軟體保護策略需要哪些政策？ *

勒索軟體保護策略需要下列原則：

* 勒索軟體偵測原則
* Snapshot原則


BlueXP  勒索軟體保護策略不需要備份原則。

* BlueXP 勒索軟體保護是否能感知 NetApp ONTAP 中的保護設定？ *

是的、 BlueXP  勒索軟體保護會探索 ONTAP 中設定的快照排程、以及在探索到的工作負載中、是否在所有磁碟區中啟用 ARP 和 FPolicy 。您最初在儀表板中看到的資訊會從其他 NetApp 解決方案和產品中彙總。

* BlueXP  勒索軟體保護是否能感知 BlueXP  備份與還原及 SnapCenter 中已制定的原則？ *

是的、如果您在 BlueXP  備份與還原或 SnapCenter 中管理工作負載、則這些產品所管理的原則將納入 BlueXP  勒索軟體保護。

* 您是否可以修改從 BlueXP  備份與還原及 / 或 SnapCenter 所執行的原則？ *

否、您無法在 BlueXP  勒索軟體保護範圍內修改由 BlueXP  備份與還原或 SnapCenter 管理的原則。您可以在 BlueXP  備份與還原或 SnapCenter 中管理這些原則的任何變更。

* 如果 ONTAP 的原則存在（已在系統管理員中啟用、例如 ARP 、 FPolicy 和快照）、這些原則是否在 BlueXP  勒索軟體保護中變更？ *

不可以 BlueXP  勒索軟體保護不會修改 ONTAP 的任何現有偵測原則（ ARP 、 FPolicy 設定）。

* 如果您在註冊 BlueXP  勒索軟體保護之後、在 BlueXP  備份與還原或 SnapCenter 中新增新原則、會發生什麼情況？ *

BlueXP  勒索軟體保護可辨識在 BlueXP  備份與還原或 SnapCenter 中建立的任何新原則。

* 您可以從 ONTAP 變更原則嗎？ *

是的、您可以在 BlueXP  勒索軟體保護中變更 ONTAP 的原則。您也可以在 BlueXP  勒索軟體保護中建立新原則、並將其套用至工作負載。此動作會以在 BlueXP  勒索軟體保護中建立的原則取代現有的 ONTAP 原則。

* 您可以停用原則嗎？ *

您可以使用 System Manager UI 、 API 或 CLI 在偵測原則中停用 ARP 。

您可以套用不包含 FPolicy 和備份原則的不同原則來停用 FPolicy 和備份原則。
