---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 開始使用 BlueXP 勒索軟體保護、驗證您的環境、網路存取、登入和網頁瀏覽器的支援。 
---
= BlueXP 勒索軟體保護先決條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
開始使用 BlueXP 勒索軟體保護、驗證您的作業環境、登入、網路存取和網頁瀏覽器是否準備就緒。

若要使用 BlueXP 勒索軟體保護、您需要下列先決條件：

* NetApp StorageGRID 或 AWS S3 中用於備份目標和存取權限集的帳戶
+
請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS 權限清單"^] 以取得詳細資料。

* 更新版本ONTAP
+
** 叢集管理 ONTAP 權限
** NetApp 自主勒索軟體保護授權、由 BlueXP 勒索軟體保護所使用、可在內部部署 ONTAP 執行個體上啟用、視您使用的 ONTAP 版本而定。請參閱 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體保護總覽"^]。
+

NOTE: BlueXP 勒索軟體保護的一般版本與 Preview 版本不同、包含 NetApp 自主勒索軟體保護技術的授權。請參閱 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體保護總覽"^] 以取得詳細資料。

+
如需更多授權詳細資料、請參閱 link:concept-ransomware-protection.html["瞭解 BlueXP 勒索軟體保護"]。



* 在 BlueXP 中：
+
** BlueXP 必須在 BlueXP 中設定每個虛擬私有雲（ VPC ）或內部部署區域的 BlueXP Connector 。請參閱 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["設定 Connector 的 BlueXP 文件"^]。
+

NOTE: 如果您有多個 BlueXP Connectors 、服務將會掃描 BlueXP UI 目前所顯示以外的所有 Connectors 資料。

** 在工作環境中啟用備份的 BlueXP 備份與還原服務
** 採用 NetApp 內部部署儲存設備（使用 NAS 或 CIFS 通訊協定）的 BlueXP 工作環境
** BlueXP 帳戶、至少有一個作用中的 Connector 連線至內部部署 ONTAP 叢集。所有來源和工作環境都必須位於相同的 BlueXP 帳戶。
** 具備帳戶管理權限的 BlueXP 使用者帳戶、可用於探索資源
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準 BlueXP 需求"^]



