---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 開始使用 BlueXP 勒索軟體保護、驗證您的環境、網路存取、登入和網頁瀏覽器的支援。 
---
= BlueXP 勒索軟體保護先決條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
開始使用 BlueXP 勒索軟體保護、驗證您的作業環境、登入、網路存取和網頁瀏覽器是否準備就緒。

若要使用 BlueXP  勒索軟體保護、您需要具備這些必要條件。



== 在 BlueXP  中

* 組織管理 Privileges 的 BlueXP  使用者帳戶，用於探索資源。
* BlueXP  組織、至少有一個使用中的 BlueXP  Connector 連線至內部部署 ONTAP 叢集、或連線至 AWS 或 Azure 中的 Cloud Volumes ONTAP 。
* BlueXP  Connector 的容器必須 `cloudmanager-ransomware-protection`處於作用中狀態。
* 在 AWS 或 Azure 中至少有一個 BlueXP  工作環境、其中有 NetApp 內部部署 ONTAP 叢集或 Cloud Volume ONTAP （使用 NAS 或 CIFS 通訊協定）。
+
** 支援使用 ONTAP OS 9.11.1 版或更新版本的 ONTAP 或 Cloud Volume ONTAP 叢集。
** 如果您的內部部署 ONTAP 叢集或 AWS 或 Azure 雲端中的 Cloud Volume ONTAP 尚未在 BlueXP  中加入、則您需要 BlueXP  Connector 。
+
請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["瞭解如何設定 BlueXP  Connector"] 和 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準 BlueXP 需求"^]。

+

NOTE: 如果您在單一 BlueXP  組織中有多個 BlueXP  Connectors 、 BlueXP  勒索軟體保護服務會掃描所有 Connector 的 ONTAP 資源、而不是目前在 BlueXP  UI 中選取的連接器。







== 在 ONTAP 9.11.1 及更新版本中

* 內部部署 ONTAP 執行個體上已啟用 ONTAP One 授權。
* NetApp 自主勒索軟體保護授權、由 BlueXP 勒索軟體保護所使用、可在內部部署 ONTAP 執行個體上啟用、視您使用的 ONTAP 版本而定。請參閱 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體保護總覽"^]。
+

NOTE: BlueXP 勒索軟體保護的一般版本與 Preview 版本不同、包含 NetApp 自主勒索軟體保護技術的授權。請參閱 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體保護總覽"^] 以取得詳細資料。

+
如需更多授權詳細資料、請參閱 link:concept-ransomware-protection.html["瞭解 BlueXP 勒索軟體保護"]。

* 若要套用保護組態（例如啟用自主勒索軟體保護等）、 BlueXP  勒索軟體保護需要 ONTAP 叢集的管理權限。ONTAP 叢集應該只能使用 ONTAP 叢集管理使用者認證來登入。
* 如果 ONTAP 叢集已使用非管理員使用者認證在 BlueXP  中登入、則必須登入 ONTAP 叢集、以必要的權限更新非管理員使用者權限、如本頁所述。




== 用於資料備份

* NetApp StorageGRID 、 AWS S3 或 Azure Blob 中用於備份目標和存取權限集的帳戶。
+
如需詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS 、 Azure 或 S3 權限清單"^] 。

* 不需要在工作環境中啟用 BlueXP  備份與還原服務。
+
BlueXP 勒索軟體保護服務可透過「設定」選項協助設定備份目的地。請參閱。 link:rp-use-settings.html["設定"]





== 更新 ONTAP 工作環境中的非管理員使用者權限

如果您需要更新特定工作環境的非管理員使用者權限、請完成這些步驟。

. 登入 BlueXP  、尋找需要更新其 ONTAP 使用者權限的工作環境。
. 按兩下工作環境以查看詳細資料。
. 按一下 * 檢視顯示使用者名稱的其他資訊 * 。
. 使用管理員使用者登入 ONTAP 叢集 CLI 。
. 顯示該使用者的現有角色。輸入：
+
[listing]
----
security login show -user-or-group-name <username>
----
. 變更使用者的角色。輸入：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 返回 BlueXP  勒索軟體保護使用者介面使用。

