---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= BlueXP 勒索軟體保護常見問題集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 存取

* 什麼是 BlueXP 勒索軟體保護 URL ？ *
對於 URL 、請在瀏覽器中輸入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 存取 BlueXP 主控台。

* 您是否需要授權才能使用 BlueXP 勒索軟體保護？ *
不需要 NetApp 授權檔案（ NLF ）。BlueXP 勒索軟體保護預覽本身不需要任何特殊授權。  所有預覽授權均為評估授權。

此服務的預覽版本需要 BlueXP 備份與還原服務授權。


TIP: 對於預覽版本、 NetApp 可協助您設定試用版和任何必要的授權。

* 如何啟用 BlueXP 勒索軟體保護？ *
BlueXP 勒索軟體保護不需要任何啟用。BlueXP 左側導覽會自動啟用勒索軟體保護選項。

如需預覽版本、您必須註冊或聯絡 NetApp 銷售代表、才能試用這項服務。然後、當您使用 BlueXP Connector 時、它會包含該服務的適當功能。

** BlueXP 勒索軟體保護是否適用於標準、受限和私有模式？ **
目前、 BlueXP 勒索軟體保護僅適用於標準模式。敬請期待更多資訊。

如需所有 BlueXP 服務中這些模式的說明、請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 部署模式"^]。

** 如何處理存取權限？ **
只有帳戶管理員才能啟動服務並探索工作負載（因為這涉及使用資源）。後續互動可由任何角色執行。

** 哪種裝置解析度最佳？ **
BlueXP 勒索軟體保護的建議裝置解析度為 1920x1080 或更高。

** 我應該使用哪個瀏覽器？ **
任何現代化的瀏覽器都能正常運作。



== 與其他服務互動

* BlueXP 勒索軟體保護是否能感知 NetApp ONTAP 中的保護設定？ *
是的、 BlueXP 勒索軟體保護會探索 ONTAP 中設定的 Snapshot 排程。

* 如果您使用 BlueXP 勒索軟體保護設定原則、您是否必須在未來僅在此服務中進行變更？ *
否、您可以從任何服務進行原則變更。



== 工作負載

** 工作負載的組成是什麼？ **
工作負載包括單一應用程式執行個體所使用的所有磁碟區。例如、部署在 ora3.host.com 上的 Oracle DB 執行個體、其資料和記錄可分別具有 vol1 和 vol2 。這些磁碟區一起構成 Oracle DB 執行個體的特定執行個體工作負載。

* BlueXP 勒索軟體保護如何優先處理工作負載資料？ *
預覽版本的資料優先順序取決於所製作的 Snapshot 複本和排程的備份。

工作負載優先順序由下列 Snapshot 頻率決定：

* * 關鍵 * ：每小時拍攝不到 1 份快照複本（極具挑戰性的保護排程）
* * 重要 * ：每天拍攝的快照複本少於 1 份、但每小時超過 1 份
* * 標準 * ：每天拍攝超過 1 份快照複本


** 新增的 Volume 、但尚未顯示 **
如果您在環境中新增了新的磁碟區、請重新啟動探索、並套用保護原則來保護該新磁碟區。

** 儀表板不會顯示我所有的工作負載。可能出了什麼問題？ **
目前僅支援 NFS 磁碟區。iSCSI 磁碟區、 CIFS 磁碟區和其他不受支援的組態會被篩選出來、不會出現在儀表板上。



== 保護原則

* BlueXP 勒索軟體原則是否與其他類型的工作負載原則共存？ *
目前、 BlueXP 備份與還原（ Cloud Backup ）支援每個磁碟區一個備份原則。因此、 BlueXP 備份與還原以及 BlueXP 勒索軟體保護功能會共用備份原則。

Snapshot 複本不受限制、可與每項服務分開新增。
