---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: 若要使用 BlueXP 勒索軟體保護、請執行幾個步驟來設定。 
---
= 設定 BlueXP 勒索軟體保護
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
若要使用 BlueXP 勒索軟體保護、請執行幾個步驟來設定。

開始之前、請先檢閱 link:rp-start-prerequisites.html["先決條件"] 確保您的環境已準備就緒。



== 準備備備份目的地

準備下列其中一個備份目的地：

* NetApp StorageGRID
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


在備份目的地本身設定選項之後、您稍後會在 BlueXP 勒索軟體保護服務中將其設定為備份目的地。如需如何在 BlueXP  勒索軟體保護中設定備份目的地的詳細link:rp-use-settings.html["設定備份目的地"]資訊，請參閱。



=== 準備 StorageGRID 成為備份目的地

如果您想要使用 StorageGRID 做為備份目的地、請參閱 https://docs.netapp.com/us-en/storagegrid-117/index.html["本文檔StorageGRID"^] 如需 StorageGRID 的詳細資訊、



=== 準備 AWS 成為備份目的地

* 在 AWS 中設定帳戶。
* 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS權限"^] 在 AWS 中。


如需在 BlueXP 中管理 AWS 儲存設備的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["管理您的Amazon S3儲存庫"^]。



=== 準備 Azure 成為備份目的地

* 在 Azure 中設定帳戶。
* 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure權限"^] 在Azure中。


如需在 BlueXP 中管理 Azure 儲存設備的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["管理 Azure 儲存帳戶"^]。



== 設定 BlueXP

下一步是設定 BlueXP 和 BlueXP 勒索軟體保護服務。

複習 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["BlueXP 標準模式要求"^]。



=== 在 BlueXP 中建立 Connector

您應聯絡 NetApp 銷售代表、試用或使用本服務。然後、當您使用 BlueXP Connector 時、它會包含勒索軟體保護服務的適當功能。

若要在使用服務之前在 BlueXP 中建立連接器，請聯絡具有建立連接器權限的 BlueXP 組織管理員，並參考描述 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何建立 BlueXP Connector"^] 。


NOTE: 如果您有多個 BlueXP Connectors 、服務將會掃描 BlueXP UI 目前所顯示以外的所有 Connectors 資料。此服務會探索與此組織相關的所有專案和所有 Connector 。
